### ISSUE TITLE
在期号编号边上同时显示这一期的名字

### ISSUE THREAD

**Issue by tongjiann** [plantree/ruanyf-weekly#1]
<img width="277" alt="image" src="https://user-images.githubusercontent.com/45749358/227403441-a6b8be5e-0d7d-45ee-b638-d83cf7e89e90.png">
个人觉在这里显示名字体验起来会更好

**Comment by baohangxing** [comment]
赞同

**Comment by baohangxing** [comment]
agree！

**Comment by plantree** [comment]
已采纳
