### ISSUE TITLE
能否把阮老师博客中的图片格式从webp转换为更通用的格式呀

### ISSUE THREAD

**Issue by Long-Ni** [plantree/ruanyf-weekly#2]

**Comment by plantree** [comment]
图片格式转换有点麻烦，后面可以考虑支持。

请问您的访问设备和浏览器版本是？

**Comment by Long-Ni** [comment]
> 图片格式转换有点麻烦，后面可以考虑支持。
> 
> 请问您的访问设备和浏览器版本是？

macOS 10.15.   safari15.16

**Comment by plantree** [comment]
![image](https://user-images.githubusercontent.com/20148487/228705996-655da345-c256-4233-963e-f3a3d12fd696.png)
![image](https://user-images.githubusercontent.com/20148487/228706049-8f00f791-c20d-42d0-b7e1-6e571b768ff6.png)

临时解决webp支持的问题，大概有两点建议：

1. 可考虑升级macOS到11

2. 安装Edge或者Chrome这种基于Chromium的浏览器，对标准支持更好

至于webp格式转换的问题，我还需要点时间调研。

希望能解决您的问题！
