### ISSUE TITLE
这都周五早上9点了，咋还没更新

### ISSUE THREAD

**Issue by terminalqo** [plantree/ruanyf-weekly#4]
持续集成行不行

**Comment by plantree** [comment]
先手动触发更新了。

根据文档https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule，

> Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. High load times include the start of every hour. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.

GitHub Action具体的调度执行时间，受到系统负载影响，不保证完全准时，另外建议不要放到**整点**。

我大致看了下，阮老师更新文章的时间大概是北京时间早晨八点钟，晚点我修改下调度策略。

感谢提醒！
