### ISSUE TITLE
请教下如何不抓取阮老师的周刊，而是自己写

### ISSUE THREAD

**Issue by chilohwei** [plantree/ruanyf-weekly#8]
最近自己在找寻合适的周刊主题，非常喜欢这个风格，也很符合我的需求，感谢作者开源～

> 下图这个 sidebar 的实现，非常喜欢

<img width="262" alt="image" src="https://github.com/plantree/ruanyf-weekly/assets/51521054/cd29da9f-8685-4531-a44d-1703b8da69b0">

不过由于本职是产品经理，不是专业的前端开发。按照自己需求在本地调试的时候，最终在 vercel 上构建失败了。所以想请教下作者：

1. 我不想抓取阮老师的周刊，想以此风格自己写周刊。该项目需要做哪些调整？

> 尝试了删除 workflows 以及 scripts 中的脚本，以及在 vercel.json 中做调整，最终还是构建失败了

2. 我不想开启 giscus 评论，不知道按照下面的操作，是否正确？

> 在`MyLayout.vue`中注释掉了下面这 2 个部分：

```vue
<template>
  <Layout>
    <template #doc-after>
      <!-- 
      <div class="giscus">
        <Giscus
          :key="giscus"
          host="https://giscus.app"
          repo="chilohwei/weekly-comment"
          repoId="668470101"
          category="General"
          categoryId="DIC_kwDOIDNWUs4CRlY7" 
          :theme="isDark ? 'dark' : 'light'"
          lang="zh-CN"
          loading="lazy"
          strict="1"
          mapping="title"
          crossorigin="anonymous"
        />
      </div>
      -->
    </template>
  </Layout>
</template>

<style>
img.pv {
  margin-top: 1em;
}
/* 屏蔽 giscus
div.giscus {
  margin-top: 2em;
}
*/
</style>
```

不知能否给予我一些帮助？非常感谢！邮箱：chilohwei@gmail.com

**Comment by plantree** [comment]
如果您想构建类似的网站，建议直接从[VitePress](https://vitepress.dev/guide/getting-started)官网最简单的demo开始，那样依赖最少。

另外，关于关闭giscus评论，您的方法是没有问题的。

如果方便，您可以创建一个repo，放一些placeholder的内容。有问题我也可以帮您看看。

祝好。
